## Steel Industry Energy Consumption
Donated on 8/13/2023
**“The dataset contains 35,040 observations, which indicates 15-minute interval energy measurements across an entire year.”**

In [52]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import figure
from sqlalchemy import create_engine


engine = create_engine(
   "postgresql://postgres:Kayman%40178@localhost:5432/energy_analytics"
)
#@ = %40

query1 = """SELECT * FROM steel_energy"""

df = pd.read_sql(query1, engine)
df.dtypes

date                                    datetime64[us]
usage_kwh                                      float64
lagging_current_reactive_power_kvarh           float64
leading_current_reactive_power_kvarh           float64
co2                                            float64
lagging_current_power_factor                   float64
leading_current_power_factor                   float64
nsm                                              int64
weekstatus                                         str
day_of_week                                        str
load_type                                          str
dtype: object

In [53]:
df.isna().sum()

date                                    0
usage_kwh                               0
lagging_current_reactive_power_kvarh    0
leading_current_reactive_power_kvarh    0
co2                                     0
lagging_current_power_factor            0
leading_current_power_factor            0
nsm                                     0
weekstatus                              0
day_of_week                             0
load_type                               0
dtype: int64

In [54]:
df["date"] = pd.to_datetime(df["date"])

In [55]:
df["hour"] = df["date"].dt.hour
df["month"] = df["date"].dt.month

In [56]:
df

,date,usage_kwh,lagging_current_reactive_power_kvarh,leading_current_reactive_power_kvarh,co2,lagging_current_power_factor,leading_current_power_factor,nsm,weekstatus,day_of_week,load_type,hour,month
0,2018-01-01 00:15:00,3.17,2.95,0.00,0.0,73.21,100.00,900,Weekday,Monday,Light_Load,0,1
1,2018-01-01 00:30:00,4.00,4.46,0.00,0.0,66.77,100.00,1800,Weekday,Monday,Light_Load,0,1
2,2018-01-01 00:45:00,3.24,3.28,0.00,0.0,70.28,100.00,2700,Weekday,Monday,Light_Load,0,1
3,2018-01-01 01:00:00,3.31,3.56,0.00,0.0,68.09,100.00,3600,Weekday,Monday,Light_Load,1,1
4,2018-01-01 01:15:00,3.82,4.50,0.00,0.0,64.72,100.00,4500,Weekday,Monday,Light_Load,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2018-12-31 23:00:00,3.85,4.86,0.00,0.0,62.10,100.00,82800,Weekday,Monday,Light_Load,23,12
35036,2018-12-31 23:15:00,3.74,3.74,0.00,0.0,70.71,100.00,83700,Weekday,Monday,Light_Load,23,12
35037,2018-12-31 23:30:00,3.78,3.17,0.07,0.0,76.62,99.98,84600,Weekday,Monday,Light_Load,23,12
35038,2018-12-31 23:45:00,3.78,3.06,0.11,0.0,77.72,99.96,85500,Weekday,Monday,Light_Load,23,12
35039,2018-12-31 00:00:00,3.67,3.02,0.07,0.0,77.22,99.98,0,Weekday,Monday,Light_Load,0,12

In [30]:
df["kW"] = df["usage_kwh"] * 4

In [31]:
md = df["kW"].max()

In [32]:
df[df["kW"] == md]

,date,usage_kwh,lagging_current_reactive_power_kvarh,leading_current_reactive_power_kvarh,co2,lagging_current_power_factor,leading_current_power_factor,nsm,weekstatus,day_of_week,load_type,hour,month,kW
31238,2018-11-22 09:45:00,157.18,77.72,0.0,0.07,89.64,100.0,35100,Weekday,Thursday,Medium_Load,9,11,628.72

In [33]:
avg_load = df["kW"].mean()

In [34]:
load_factor = avg_load/md

In [35]:
df['lagging_current_power_factor'].mean()

np.float64(80.5780562214612)

In [36]:
df[df["lagging_current_power_factor"] < 0.85]

,date,usage_kwh,lagging_current_reactive_power_kvarh,leading_current_reactive_power_kvarh,co2,lagging_current_power_factor,leading_current_power_factor,nsm,weekstatus,day_of_week,load_type,hour,month,kW
29855,2018-11-07,0.0,0.0,0.0,0.0,0.0,0.0,0,Weekday,Wednesday,Light_Load,0,11,0.0

In [38]:
df["day"] = df["date"].dt.dayofweek

In [39]:
def classify_time(row):
    if row["day"] < 5 and 8 <= row["hour"] < 22:
        return "Peak"
    else:
        return "Off-Peak"

df["time_category"] = df.apply(classify_time, axis=1)

In [40]:
df.groupby("time_category")["usage_kwh"].sum()

time_category
Off-Peak    180115.00
Peak        779521.71
Name: usage_kwh, dtype: float64

In [41]:
df.groupby("load_type")["usage_kwh"].sum()

load_type
Light_Load      155892.81
Maximum_Load    430977.36
Medium_Load     372766.54
Name: usage_kwh, dtype: float64

In [45]:
peak = df.loc[df["kW"].idxmax()] # check for load_type, day_of_week, hour
peak

date                                    2018-11-22 09:45:00
usage_kwh                                            157.18
lagging_current_reactive_power_kvarh                  77.72
leading_current_reactive_power_kvarh                    0.0
co2                                                    0.07
lagging_current_power_factor                          89.64
leading_current_power_factor                          100.0
nsm                                                   35100
weekstatus                                          Weekday
day_of_week                                        Thursday
load_type                                       Medium_Load
hour                                                      9
month                                                    11
kW                                                   628.72
day                                                       3
time_category                                          Peak
Name: 31238, dtype: object

In [46]:
df.groupby(["hour"])["usage_kwh"].mean()

hour
0      7.870075
1      6.072479
2      4.428390
3      4.358041
4      4.309438
5      4.245548
6      4.223705
7      4.502075
8     37.704795
9     58.551733
10    55.874733
11    57.097459
12    18.461000
13    39.019500
14    56.155260
15    55.637541
16    55.799582
17    43.833096
18    33.020932
19    38.208514
20    37.477226
21    13.777363
22     8.658918
23     7.998014
Name: usage_kwh, dtype: float64

In [51]:
peak_kwh = df[df["time_category"]=="Peak"]["usage_kwh"].sum()
off_kwh = df[df["time_category"]=="Off-Peak"]["usage_kwh"].sum()

cost = peak_kwh * 0.365 + off_kwh * 0.292
print(f"TNB cost: {cost}")
md_cost = md * 30.30
print(f"Maximum Demand: {md_cost}")

TNB cost: 337119.00415
Maximum Demand: 19050.216